const departamentos = ["Alta Verapaz",
"Baja Verapaz",
"Chimaltenago",
"Chiquimula",
"Guatemala",
"El Progreso",
"Escuintla",
"Huehuetenango",
"Izabal",
"Jalapa",
"Jutiapa",
"Petén",
"Quetzaltenango",
"Quiché",
"Retalhuleu",
"Sacatepequez",
"San Marcos",
"Santa Rosa",
"Sololá",
"Suchitepequez",
"Totonicapán",
"Zacapa"]

export default departamentos;