apiVersion: v1
kind: Namespace
metadata:
  name: aplicacion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: servidor
  name: servidor
  namespace: aplicacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servidor
  template:
    metadata:
      labels:
        app: servidor
    spec:
      containers:
      - image: rickg96/so1-server
        imagePullPolicy: Always
        name: servidor
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: servidor
  name: servidor
  namespace: aplicacion
spec:
  type: NodePort
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    app: servidor
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cliente
  name: cliente-svc
  namespace: aplicacion
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cliente