apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cliente
  name: cliente
  namespace: aplicacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliente
  template:
    metadata:
      labels:
        app: cliente
    spec:
      containers:
      - image: douglasmartinez97/so1-client
        imagePullPolicy: Always
        name: cliente
